### ISSUE TITLE
TurboPFor is still active

### ISSUE THREAD

**Issue by powturbo** [mayeranalytics/turbopfor_rs#1]
The [turbopfor](https://github.com/powturbo/TurboPFor-Integer-Compression) library is still active, maintained and extended.
I've not responded to the issues since months because of laking of time. 
Your readme is full of unfunded critics and disrespect. You are stating that the source is buggy without showing what's wrong.
Unlike other libraries, TurboPFor is working with arbitrary files and full integer range without crashing.

Yes there is not a separate documentation, but you'll find allmost all functions with limited documentation in the header files.
The general template is documented in the readme file and the usage of the functions are as simple as memcpy.
What you are describing as "abundance of superlatives" is simply fact based and is  only the interpretation of benchmark numbers.
Until today there is no other library that has nearly the functionality, efficiency and the speed of TurboPFor. 
Because of speed and complexity of the software TurboPFor is reading/writing beyond the i/o buffers. 
I'll document the slop rquirements in the next weeks. Maybe I'll adress also this issue.

**Comment by mayeranalytics** [comment]
I don't mean to diminish your accomplishment. But when it comes to using turbopfor in other projects I feel I should convey my own reservations. I think my statements were factually correct at time of writing:

1. "The library is still active, maintained and extended." -> Great! I will change my statement.
2. "You are stating that the source is buggy without showing what's wrong." -> The patch shows what's wrong.
3. "Unlike other libraries, TurboPFor is working with arbitrary files and full integer range without crashing." -> Not crashing is not the same as being bug-free.
4. "but you'll find allmost all functions with limited documentation in the header files" -> The limited documentation is exactly what I am complaining about.
5. "The general template is documented in the readme file and the usage of the functions are as simple as memcpy.": No it is not as simple as memcpy! You need to know how much buffer, including overflow, to allocate. So, please, stop saying things that are misleading.
6. "abundance of superlatives" -> It just looks too much like marketing to me, I'm getting allergic to the "blazingly fast" that spreads like an epidemic. In this case it is statements like "as simple as memcpy" that just annoy me. And you are setting a very high bar for yourself - in a way you are setting yourself up for failure.

All that said: Thank you sharing turbopfor and for your continuing effort!

**Comment by powturbo** [comment]
2. Nobody can claim assuredly that some software package is bug-free. Your statement sounds like that TurboPFor is full of bugs. witch is simply not true. If you find a bug than open an issue, it will be addressed as time permits.
3. limited documentation. Well almost all TurboPFor function use the same calling convention. There are nearly 1000 functions and I'll cerainly not write a documentation for every function. Nevertheless I'll try to extend the documentation in the header files. 
5. Yes, it is as simple as memcpy because the calls are similiar. You have nothing to set configure or initialize before calling the functions, just one single call. TurboPFor is encoding/decoding and you must know the buffer size for the i/o buffers. This is valid for all encoding/compression software.  I'll document the buffer requirements next time in the readme and the header files. I'll try to find a way to avoid reading/writing above the exact buffer lengths.
6. It's also marketing and why not? It's easy to verify the claims, just download and try icapp.
Unlike other benchmarks or claims, my benchmarks are comparing TurboPFor against the best of the best integer compression packages. Others are simply ignoring the existence of TurboPFor.
If you have a problem with ads/marketing then don't use internet. 
Have a nice day and thank you for your comments.

**Comment by mayeranalytics** [comment]
I think we can co-exist without agreeing on every point.
So, what do you want me to do? Shall I call it "not production ready" instead of "buggy"?

**Comment by powturbo** [comment]
TurboPFor is already used in production. Despite the issue with reading/writing above the array length, witch is disapearing
when you allocate the proper sizes, I'm actually not aware of any issue causing the package to crash or delivering wrong results.
Your mentioned bug is already corrected. The icapp can process arbitrary  files without crashing or delivering wrong results.
It's  ALWAYS checking that the decompressed output is matching the original input. I can't dictate what to write or not, simply stay by the facts.

**Comment by mayeranalytics** [comment]
Ok.
If you believe it is production ready you should write that in the README.

**Comment by mayeranalytics** [comment]
I updated the readme and adapted to 2023-04. Thank you for your efforts.

**Comment by powturbo** [comment]
Thank you,
there are some changes in the latest version. As stated in the Readme under Knowns issues:
- Actually (2023.04) there are no known issues or bugs
- The TurboPFor functions can work with arbitrary inputs
- TurboPFor does normally not read outside the input (encode/decode) buffers and does not write outside the output buffer at decoding.
- TurboPFor does not write above a properly sized output buffers at encoding. Use the bound (ex. v8bound,p4bound) functions to allocate a max. memory output buffer.

- There is also new rust bindings.

- icapp can read:
1 - raw (binary) files (default mode).
2 - text (1 integer/line)  wih option -Ft, 
3 - Text (numbers separated by non numercic character. ex: comma) with option -Fc
4 - csv files option -Ft and -K# where # = column number

Default is 32 bits integers. For 8,16 or 64 bits integers use the modifiers b, s or l 
and for floats or double use f,d in the "-F" option.
Example: -Fs or -Fcs, -Fts for 16 bits integers or -Fd for 64-bits floating point numbers. 

See also the several examples in the readme.
